added/reworked content to robotics and xlab projects
burglabs/knowledge-xlab pull request #19
Opened 2021-05-28 09:58 UTC by fraujaeger

2021-05-28 10:21 UTC, alexabruck commented
@fraujaeger How come there are 83 files changed? :-)

2021-05-28 11:31 UTC, fraujaeger commented
I don't know why there are seemingly changes in every file. The files i didn't touch are exactly the same of the main branch.

2021-05-28 11:33 UTC, fraujaeger commented
Should i do another pull request without the files i didn't change?

2021-05-28 12:50 UTC, alexabruck commented
@fraujaeger So you didn't change the files? I wonder why git detects a change in them.. Could you find out? Maybe its the result of some auto-formatting you activated in your code editor (e.g. adding spaces or tabs etc.)

2021-05-31 13:06 UTC, simonmaris commented
this was due to a stupid problem with CRLF and LF line endings being different between macos and windows.. 

After working through the git documentation / stackoverflow, I was slightly confused, what would be the way to go. This post helped clear things up a little bit: https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/

I have now normalized everything and introduced a .gitattributes file, which should take care of this with and for all current and future contributors.. 

So, I guess, problem fixed.. Time to review this giant PR :)

2021-06-03 09:12 UTC, simonmaris requested changes
I skimmed through most files, content looks good, the general points as commented are:

- no html, let's find another way for image captions
- clearer use of tags (and aliases)

2021-06-03 09:12 UTC, simonmaris commented on Collaborative Robot.md
> +tags: industrial robot UR
these tags are all interpreted, no comma necessary. However, this means we currently have the tags _robot_, _robotics_ and _Robotic_, not very clear.. you can enable the core plugin _Tag Pane_ in Obsidian to get an overview and sort this a little bit..

2021-06-03 09:12 UTC, simonmaris commented on Control Box.md
> +*Learn more about the Control Box at [UR acadamy](https://academy.universal-robots.com/free-e-learning/cb3-e-learning/) Lesson 1.*
typo

2021-06-14 12:08 UTC, merged